### FINAL FIGURES #############################################################

source("R/01 helper_functions.R")


## FIGURE 1. MAP OF BANQ AREA (WITH NO BUFFERS AT ALL)



## FIGURE 2. MAP OF BANQ AREA (WITH BANQ BUFFER DRAWN ON)



## FIGURE 3. MAP OF MONTREAL WITH ALL LIBRARY BUFFERS



## FIGURE 4. LOLLIPOP GRAPH OF 2016 CORE HOUSING NEED ACROSS ALL REGIONS



## FIGURE 5. 2006/2016 CORE HOUSING NEED COMPARISON ACROSS ALL REGIONS



## FIGURE 6. ALL FIVE VARIABLE 2006/2016 COMPARISONS ACROSS ALL REGIONS


